export const MAX_REFRESH_TOKENS_FOR_USER = 5;
export const MAX_PASSWORD_SYMBOLS = 20;

export const ACTIVATION_CODE_EXPIRE_IN = 60 * 5;
export const ACTIVATION_CODE_ATTEMPTS_LIMIT = 3;
export const ACTIVATION_CODE_REQUEST_INTERVAL_SECONDS = 60;
